### ISSUE TITLE
Many times lib file is not produced

### ISSUE THREAD

**Issue by davidsanda** [3F/DllExport#77]
With direct cmake config, dllexport sometimes fails to produce the lib. Here is the  the minimal testcase.
Just run cmake [path to source] and appli dllexport. No lib files gets produced, because the trigger to process the dll does not work. 

Also, if you click apply, when the project file is already modified, it crashes on something proj file related. 
[minimal.zip](https://github.com/3F/DllExport/files/2096311/minimal.zip)

**Comment by 3F** [comment]
Thanks for the report and especially for the minimal testcase!
I will look into later.

> Also, if you click apply, when the project file is already modified, it crashes on something proj file related.

I checked one below. Is this same for you or it unhandled exception at all ?
```
System.ArgumentException: The node is not parented by this object so it cannot be removed from it.
   at Microsoft.Build.Shared.ErrorUtilities.ThrowArgument(Exception innerException, String resourceName, Object[] args)
   at Microsoft.Build.Construction.ProjectElementContainer.RemoveChild(ProjectElement child)
   at net.r_eg.MvsSln.Core.XProject.RemoveImport(ImportElement element) in D:\prg\projects\MvsSln\MvsSln\MvsSln\Core\XProject.cs:line 199
   at net.r_eg.DllExport.Wizard.Project.RemoveDllExportLib() in D:\prg\projects\DllExport\DllExport\Wizard\Project.cs:line 528
   at net.r_eg.DllExport.Wizard.Project.ActionConfigure() in D:\prg\projects\DllExport\DllExport\Wizard\Project.cs:line 277
   at net.r_eg.DllExport.Wizard.Project.Configure(ActionType type) in D:\prg\projects\DllExport\DllExport\Wizard\Project.cs:line 217
   at net.r_eg.DllExport.Wizard.UI.ConfiguratorForm.btnApply_Click(Object sender, EventArgs e) in D:\prg\projects\DllExport\DllExport\Wizard\UI\ConfiguratorForm.cs:line 200
```

**Comment by davidsanda** [comment]
Yes, the same.

**Comment by davidsanda** [comment]
Hi Denis, do you have any timeframe for the fixes? Doing it manually is
such a pain:)

thanks

David

**Comment by 3F** [comment]
I'm sorry about this :( A lot of problems in my life still affects my 
time. But I think (I really hope) I'll find time in this month for most 
problems in several important my open projects. It should be at least 
DllExport, MvsSln, vsSBE, and probably Conari (well, we'll see).

Thus, I'll try to start for DllExport at the end of the next week, i.e. 
~12-15.

I hope it will be trivial issue :) By the way, an unhandled exception is 
related (seems like) for MvsSln/original MS libraries part. You can also 
try to look similar issues from that project.
Anyone else may also try to fix something.

Hope for understanding.


05.07.2018 23:52, davidsanda:

**Comment by davidsanda** [comment]
Hi Denis, there is a problem in my code, which is likely related to
3f/dllexport, which i described in here:
https://stackoverflow.com/questions/51209370/c-sharp-4-7-2-crash-in-clr-dll-when-debugging-and-starting-from-native

The situation is not related to any actual parameters in the base class. It
simply crashes as described at the place. Do you have any suggestion as to
where to start looking? The crash is access violation in crl.dll, but the
fact, it only happens when in unmanaged->managed, is completely baffling to
me.
thanks for any advice, if you find it relevant..

**Comment by 3F** [comment]
David,

Before me, you can try to isolate incorrect VA for clr.dll. Try also inspect manually via memory tool with disassembling for native instructions (non IL).

What about architecture? seems your host side x64, can you check for x86 (of course for both modules).

Check also .ctor body before calling your base type ~`call instance {...}::.ctor()`, and any defs that may affect on stack before calling. 

Is this reproducible for any derived class? steps?

By the way, try Conari engine if you're using native/unmanaged code/librraies inside clr (host side).

**Comment by davidsanda** [comment]
Splendid! What link or server url should i put in there?
David

**Comment by 3F** [comment]
Temporarily please use from ci.appveyor.com. For `-pkg-link` it should be like:

```
DllExport -pkg-link https://ci.appveyor.com/api/buildjobs/ng0kg9yhm0x85y90/artifacts/bin/Release/DllExport.1.6.0.nupkg -action Configure
```

I mean, [I also added](https://plus.google.com/+DenisKuzmin3F/posts/CroY5HZZVZU) `GitHub Releases` for new artefacts, but seems we have some other problem:

```
The request was aborted: Could not create SSL/TLS secure channel.
```

Don't worry, [I'll fix it](https://plus.google.com/+DenisKuzmin3F/posts/LtpKLgnAkWX) too :)

**Comment by davidsanda** [comment]
Hi Denis, looks like something is off. When i do as you hint, it failes to
compile(and produce the lib) with this error:
Severity    Code    Description    Project    File    Line    Suppression
State
Error        The "DllExportAppDomainIsolatedTask" task could not be
instantiated from
"C:\esqgame-code\server-bin\packages\DllExport.1.6.0\tools\RGiesecke.DllExport.MSBuild.dll".
Could not load file or assembly 'RGiesecke.DllExport.MSBuild,
Version=1.6.0.20318, Culture=neutral, PublicKeyToken=a15ccd98f2d61726' or
one of its dependencies. Operation is not supported. (Exception from
HRESULT: 0x80131515)    esq_managed_core

**Comment by 3F** [comment]
David, did you remove the old packages before new? the command 
`DllExport -pkg-link {url} ...` requires an removing manually.

15.07.2018 16:34, davidsanda:

**Comment by 3F** [comment]
@davidsanda I fixed problem with `SSL/TLS secure channel`. Thus, you can also use packages from GitHub, e.g.:

`DllExport -pkg-link https://github.com/3F/DllExport/releases/download/CI-build-83/DllExport.1.6.0.nupkg -action Configure`

**Comment by davidsanda** [comment]
:)
c:\esqgame-code\server-bin>DllExport -pkg-link
https://github.com/3F/DllExport/releases/download/CI-build-83/DllExport.1.6.0.nupkg
-action Configure
The request was aborted: Could not create SSL/TLS secure channel.
Something went wrong. Try to use another keys.

**Comment by davidsanda** [comment]
Anyway, with direct link to ci server, i can call the configure command
repeatedly and it does not crash. However, lib for linking with c++ is not
generated, so that part of bug is not fixed yet.

By the way, about the crash i mentioned recently. I nailed it in asm to
some static call to reserved region of memory.

**Comment by 3F** [comment]
> The request was aborted: Could not create SSL/TLS secure channel.

Is this new version of DllExport.bat? from https://github.com/3F/DllExport/releases/download/CI-build-83/DllExport.bat

DllExport -version
```
v1.6.0.21418 [ 9c89fac ]
```

> However, lib for linking with c++ is not generated, so that part of bug is not fixed yet. 

yes, because this issue contains two related bugs, and I fixed only one of this :) Please wait, as I said:

> I'll push the fixes soon after some checking.

**Comment by 3F** [comment]
> I nailed it in asm to some static call to reserved region of memory.

please for details in #79

**Comment by 3F** [comment]
@davidsanda, Please check the final fixes via efddbdb. I added new support of groups exactly for MvsSln.

See build-84 from GHR

**Comment by davidsanda** [comment]
It works:)

**Comment by 3F** [comment]
> It works:)

Good! This changes was planned for v1.6.1

*About #79, I'm waiting additional details for how to reproduce if this bug still is related to our project.*
